### ISSUE TITLE
QML Viewer causes reboot

### ISSUE THREAD

**Issue by roydenyates** [tim-sueberkrueb/qmlviewer#1] opened 2016-09-05 22:39 UTC
Mx4 rc-proposed. Open ML viewer as the only open app. Right swipe to app spread. Up swipe QML viewer to close. System goes to reboot.

If you open spread but move the QML viewer app around a bit (move the spread back and forth) the dismiss works just fine.

Or so it seems. Found this one difficult to pin down...

**Comment by roydenyates** [comment] 2016-09-05 23:04
Difference between a spread that causes the reboot and one that works, is very slight.

**Comment by timsueberkrueb** [comment] 2016-09-06 17:52
Hey @roydenyates! Thanks for opening an issue.
Can you please reproduce the issue again and then paste `~/.cache/upstart/unity8.log` to the pastebin of your choice (e.g. http://paste.ubuntu.com/)?
EDIT: I wasn't able to reproduce the problem on BQ E4.5 (krillin) rc-proposed. Is there anything special you did (e.g. opening a specific file)?

**Comment by roydenyates** [comment] 2016-09-06 22:14
Log as requested: http://paste.ubuntu.com/23143317/

I am doing nothing but opening the app and then closing it from the spread. It is a little variable- a moment ago, I had it reboot even when I up-swiped AFTER "jiggling" the spread around a bit, something that earlier seemed not to cause a reboot. Frankly, sometimes it closes just fine and other times not. A clean swipe to spread seems the most reliable way.

Either way, I have just rebooted the device a number of times this way.

**Comment by BlueKenny** [comment] 2017-12-10 14:23
Great App :)
PS i think we can close this bug ;)

**Comment by timsueberkrueb** [comment] 2017-12-10 16:16
> Great App :)

Glad you like it @BlueKenny :)

>  PS i think we can close this bug ;)

Yes. I'm closing the issue since I it's over a year old and I couldn't reproduce it.

However, please note that this project is not being actively maintained right now.

**Closed as completed by timsueberkrueb** 2017-12-10 16:16 UTC
